import type { Metadata } from "next";
import { Exo, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/sharedComponents/Navbar";
import Footer from "@/sharedComponents/Footer";
import DraggableImage from "./homeComponents/DraggableImage";
import { CartProvider } from "@/store/CartContext";
import { ToastProvider } from "@radix-ui/react-toast";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const exo = Exo({
  subsets: ['latin'],
  variable: '--font-exo',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ToastProvider>
      <CartProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-b from-[#000] to-[#1a1a1a] antialiased flex flex-col min-w-screen h-full min-h-screen scrollbar-custom justify-between items-center`}
          >
            <div className="absolute w-full max-w-screen h-full mx-auto flex items-center justify-center overflow-hidden">
              <div className="line ml-[50%]"></div>
              <div className="line ml-[25%]"></div>
              <div className="line"></div>
              <div className="line mr-[25%]"></div>
              <div className="line mr-[50%]"></div>
            </div>
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </body>
        </html>
      </CartProvider>
    </ToastProvider>
  );
}
